export function LiabilityDisclaimerPage() {
  const handleBackClick = () => {
    window.location.href = '/legal';
  };

  return (
    <div className="h-screen bg-[var(--app-bg)] flex flex-col overflow-hidden">
      {/* Header with Back Button - Fixed */}
      <div className="border-b border-[var(--card-border)] bg-[var(--card-bg)] flex-shrink-0">
        <div className="max-w-4xl mx-auto px-6 py-4">
          <button
            onClick={handleBackClick}
            className="flex items-center gap-2 text-[var(--text-primary)] hover:text-[#5A5BEF] transition-colors mb-4"
          >
            <span className="text-sm font-medium">← Back to Legal</span>
          </button>
          <h1 className="text-3xl font-semibold text-[var(--text-primary)]">Liability Disclaimer</h1>
          <p className="text-sm text-[var(--text-secondary)] dark:text-[#A0A0A0] mt-2">Last Updated: 02/11/2025</p>
        </div>
      </div>

      {/* Content - Scrollable */}
      <div className="flex-1 overflow-y-auto">
        <div className="max-w-4xl mx-auto px-6 py-8">
          <div className="prose prose-invert max-w-none">
            <div className="space-y-6 text-[var(--text-primary)]">
              <section>
                <h2 className="text-2xl font-semibold text-[var(--text-primary)] mb-3">1. Introduction</h2>
                <p className="text-[var(--text-secondary)] dark:text-[#A0A0A0] leading-relaxed">
                  This Liability Disclaimer ("Disclaimer") applies to all users of Petros ("Platform") operated by Kaipullha Techlabs Private Limited ("Company", "we", "our", "us"). By accessing or using the Platform, you acknowledge and agree to the terms outlined below.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-[var(--text-primary)] mb-3">2. Nature of Service</h2>
                <p className="text-[var(--text-secondary)] dark:text-[#A0A0A0] leading-relaxed">
                  The Platform provides AI-assisted tutoring designed to aid learning, comprehension, and revision. The Platform does not replace professional educators, certified tutors, or academic advisors. All information, explanations, and suggestions generated by the AI system are for informational and educational purposes only.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-[var(--text-primary)] mb-3">3. No Guarantee of Accuracy or Results</h2>
                <p className="text-[var(--text-secondary)] dark:text-[#A0A0A0] leading-relaxed mb-3">
                  While the Company strives to ensure quality and accuracy in AI-generated content, we do not guarantee:
                </p>
                <ul className="list-disc list-inside space-y-2 text-[var(--text-secondary)] dark:text-[#A0A0A0] ml-4">
                  <li className="leading-relaxed">The correctness, completeness, or reliability of responses.</li>
                  <li className="leading-relaxed">Achievement of specific learning outcomes, grades, or professional results.</li>
                  <li className="leading-relaxed">Uninterrupted availability or error-free operation of the Platform.</li>
                </ul>
                <p className="text-[var(--text-secondary)] dark:text-[#A0A0A0] leading-relaxed mt-3">
                  Users are advised to verify all outputs independently and exercise their own judgment before relying on AI-generated information.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-[var(--text-primary)] mb-3">4. Limitation of Liability</h2>
                <p className="text-[var(--text-secondary)] dark:text-[#A0A0A0] leading-relaxed mb-3">
                  To the maximum extent permitted by law, Kaipullha Techlabs Pvt. Ltd., its directors, employees, and affiliates shall not be liable for any direct, indirect, incidental, consequential, or punitive damages arising from:
                </p>
                <ul className="list-disc list-inside space-y-2 text-[var(--text-secondary)] dark:text-[#A0A0A0] ml-4">
                  <li className="leading-relaxed">Use or inability to use the Platform.</li>
                  <li className="leading-relaxed">Errors or inaccuracies in AI outputs.</li>
                  <li className="leading-relaxed">Service interruptions, delays, or data losses.</li>
                  <li className="leading-relaxed">Unauthorized access, hacking, or breaches.</li>
                  <li className="leading-relaxed">Academic, financial, or reputational consequences of using the Platform.</li>
                </ul>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-[var(--text-primary)] mb-3">5. User Responsibility</h2>
                <p className="text-[var(--text-secondary)] dark:text-[#A0A0A0] leading-relaxed mb-3">
                  Users assume full responsibility for:
                </p>
                <ul className="list-disc list-inside space-y-2 text-[var(--text-secondary)] dark:text-[#A0A0A0] ml-4">
                  <li className="leading-relaxed">The interpretation and use of AI-generated responses.</li>
                  <li className="leading-relaxed">Compliance with local laws, institutional codes, and academic integrity standards.</li>
                  <li className="leading-relaxed">Ensuring that minors use the Platform under supervision, without enabling NSFW or restricted content.</li>
                </ul>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-[var(--text-primary)] mb-3">6. Third-Party Services</h2>
                <p className="text-[var(--text-secondary)] dark:text-[#A0A0A0] leading-relaxed">
                  The Platform may integrate third-party tools or APIs (e.g., payment gateways, cloud storage). The Company bears no responsibility for the performance, reliability, or policies of such external providers.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-[var(--text-primary)] mb-3">7. Indemnification</h2>
                <p className="text-[var(--text-secondary)] dark:text-[#A0A0A0] leading-relaxed">
                  You agree to indemnify, defend, and hold harmless Kaipullha Techlabs Pvt. Ltd., its affiliates, officers, and employees from any claims, damages, or expenses arising out of your violation of the Terms, misuse of the Platform, or infringement of third-party rights.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-[var(--text-primary)] mb-3">8. Service Availability</h2>
                <p className="text-[var(--text-secondary)] dark:text-[#A0A0A0] leading-relaxed">
                  The Platform may undergo maintenance, upgrades, or interruptions. The Company reserves the right to suspend or discontinue services at any time without liability for data loss or downtime.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-[var(--text-primary)] mb-3">9. No Legal or Professional Advice</h2>
                <p className="text-[var(--text-secondary)] dark:text-[#A0A0A0] leading-relaxed">
                  The AI tutor does not provide legal, medical, financial, or other professional advice. Any reliance on AI-generated information in such contexts is entirely at the user's discretion and risk.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-[var(--text-primary)] mb-3">10. Governing Law & Jurisdiction</h2>
                <p className="text-[var(--text-secondary)] dark:text-[#A0A0A0] leading-relaxed">
                  This Disclaimer shall be governed by and construed in accordance with the laws of India, with exclusive jurisdiction vested in the courts of Chennai, Tamil Nadu.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-[var(--text-primary)] mb-3">11. Contact Information</h2>
                <p className="text-[var(--text-secondary)] dark:text-[#A0A0A0] leading-relaxed mb-2">
                  For questions or clarifications regarding this Disclaimer:
                </p>
                <div className="text-[var(--text-secondary)] dark:text-[#A0A0A0] space-y-1">
                  <p><strong className="text-[var(--text-primary)]">Kaipullha Techlabs Private Limited</strong></p>
                  <p>Email: <a href="mailto:danesh@decivise.com" className="text-[#5A5BEF] hover:underline">danesh@decivise.com</a></p>
                  <p>Jurisdiction: Chennai, Tamil Nadu, India</p>
                </div>
              </section>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

